# shellcheck shell=bash
# Shared helpers for the Pi-Bolt scripts. Sourced, not run.
set -euo pipefail
# (mapfile, and empty arrays under set -u: bash 4.4. macOS's /bin/bash is 3.2: brew install bash.)
if [ "${BASH_VERSINFO[0]}" -lt 4 ] || { [ "${BASH_VERSINFO[0]}" -eq 4 ] && [ "${BASH_VERSINFO[1]}" -lt 4 ]; }; then
	printf 'error: bash 4.4 or later is required (this is %s); on macOS: brew install bash\n' "$BASH_VERSION" >&2
	exit 1
fi

PIBOLT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
# Where sources, toolchains and builds live; override with PIBOLT_WORK.
PIBOLT_WORK="${PIBOLT_WORK:-$PIBOLT_ROOT/.work}"
# The Pi to build: this repository, which is a fork of Pi. Override with PIBOLT_PI or --pi.
PIBOLT_PI="${PIBOLT_PI:-$PIBOLT_ROOT}"

log() { printf '\033[1;36m==>\033[0m %s\n' "$*" >&2; }
warn() { printf '\033[1;33mwarning:\033[0m %s\n' "$*" >&2; }
die() { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

need() { command -v "$1" >/dev/null 2>&1 || die "'$1' is required but not installed"; }

# The platform, as builds and release files are named: linux-x64, darwin-arm64.
case "$(uname -s)" in
Linux) PIBOLT_OS=linux ;;
Darwin) PIBOLT_OS=darwin ;;
*) PIBOLT_OS="$(uname -s | tr '[:upper:]' '[:lower:]')" ;;
esac
case "$(uname -m)" in
x86_64 | amd64) PIBOLT_ARCH=x64 ;;
arm64 | aarch64) PIBOLT_ARCH=arm64 ;;
*) PIBOLT_ARCH="$(uname -m)" ;;
esac
# shellcheck disable=SC2034 # for the scripts that source this
PIBOLT_PLATFORM="$PIBOLT_OS-$PIBOLT_ARCH"

# abspath PATH: PATH made absolute with symbolic links resolved, whether or not it exists (GNU realpath -m; macOS has no -m).
abspath() { python3 -c 'import os,sys; print(os.path.realpath(sys.argv[1]))' "$1"; }

# timeout SECONDS COMMAND...: GNU timeout where there is one; on macOS a stand-in on PATH (an executable, so that `env ... timeout`
# finds it too) with perl's alarm: killed by SIGALRM, status 142 instead of 124.
if ! command -v timeout >/dev/null 2>&1; then
	if [ ! -x "$PIBOLT_WORK/bin/timeout" ]; then
		mkdir -p "$PIBOLT_WORK/bin"
		# shellcheck disable=SC2016 # perl, not shell
		printf '#!/usr/bin/perl\nalarm shift; exec { $ARGV[0] } @ARGV or exit 127;\n' >"$PIBOLT_WORK/bin/timeout"
		chmod +x "$PIBOLT_WORK/bin/timeout"
	fi
	PATH="$PIBOLT_WORK/bin:$PATH"
fi

# sha256 [ARGS]: sha256sum, or shasum -a 256 where there is none (older macOS). Same output.
sha256() { if command -v sha256sum >/dev/null 2>&1; then sha256sum "$@"; else shasum -a 256 "$@"; fi; }

# check_sum DIR FILE: whether DIR/FILE matches its line in DIR/SHA256SUMS. No line is a mismatch: macOS's sha256sum passes when
# it is given nothing to check.
check_sum() {
	local line
	line=$(grep " $2\$" "$1/SHA256SUMS") && [ -n "$line" ] || return 1
	if command -v sha256sum >/dev/null 2>&1; then
		(cd "$1" && printf '%s\n' "$line" | sha256sum -c --quiet - >/dev/null 2>&1)
	else
		(cd "$1" && printf '%s\n' "$line" | shasum -a 256 -c --status - 2>/dev/null)
	fi
}

# source_field <component> <field>: a value from sources.json.
source_field() {
	python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))[sys.argv[2]].get(sys.argv[3], ""))' "$PIBOLT_ROOT/sources.json" "$1" "$2"
}

# The Bun runtime with the ahead-of-time engine: an explicit PIBOLT_BUN, else the one build-runtime.sh made.
runtime_bun() {
	local bun="${PIBOLT_BUN:-$PIBOLT_WORK/runtime/bun}"
	[ -x "$bun" ] || die "no Pi-Bolt runtime at $bun: run scripts/build-runtime.sh, or set PIBOLT_BUN"
	printf '%s\n' "$bun"
}

# Pi's coding-agent package in a Pi checkout that has been built, and its version.
pi_agent_dir() {
	local agent
	agent="$(realpath "$1")/packages/coding-agent"
	[ -f "$agent/dist/bun/cli.js" ] || die "$agent/dist/bun/cli.js not found: build Pi first (scripts/prepare-pi.sh)"
	printf '%s\n' "$agent"
}
pi_version() {
	python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["version"])' "$1/package.json"
}

# stage_plugins <agent dir> <manifest>: copies the manifest's folder into the Pi tree and writes the entry point that starts Pi
# with those extensions. Inside the Pi tree, the packages Pi provides to extensions (@earendil-works/pi-*, typebox) resolve to
# Pi's own modules, as they do when Pi loads an extension at run time; a copy of one inside the plugin would be a second Pi
# (duplicate classes and registries), so those are left out. Prints the entry, relative to the agent dir. The caller removes
# "$1/.pibolt-plugins" when done.
stage_plugins() {
	local agent="$1" manifest="$2" stage src
	[ -f "$manifest" ] || die "--plugins: $manifest not found"
	need rsync
	stage="$agent/.pibolt-plugins"
	src="$(dirname "$(realpath "$manifest")")"
	rm -rf "$stage" && mkdir -p "$stage"
	rsync -a --exclude .git --exclude 'node_modules/@earendil-works/pi-*' --exclude 'node_modules/typebox' "$src/" "$stage/src/"
	cat >"$stage/entry.ts" <<-EOT
		// Generated by Pi-Bolt: Pi's Bun entry (packages/coding-agent/src/bun/cli.ts), with extensions compiled in.
		import "../dist/bun/sandbox-env-setup.js";
		// (\`pi-bolt --version\` answered before the rest of Pi, and the plugins, are loaded: as Pi's own entry does.)
		import "../dist/bun/version-fast-path.js";
		import "../dist/bun/runtime-setup.js";
		import { setupCli } from "../dist/cli/setup.js";
		import { main } from "../dist/main.js";
		import plugins from "./src/$(basename "$manifest")";

		// A named plugin is a built-in extension (\`builtin:<name>\`): it can be turned off (\`-builtin:<name>\` in the \`extensions\`
		// setting, or the config screen), and an extension of the same tools loaded at run time replaces it (replaceable) instead of
		// conflicting. The manifest decides where it says (builtin or replaceable set); an unnamed factory stays an inline extension.
		const extensionFactories = plugins.map((plugin) =>
			typeof plugin === "function" || plugin.builtin !== undefined
				? plugin
				: { ...plugin, builtin: true, replaceable: plugin.replaceable ?? true },
		);

		setupCli();
		main(process.argv.slice(2), { extensionFactories });
	EOT
	printf '%s\n' ./.pibolt-plugins/entry.ts
}

# Pi's entry points: its Bun entry (or $1, a staged plugin entry) and the workers it starts (package.json build:binary).
pi_entries() {
	local agent="$1" entry="${2:-./dist/bun/cli.js}"
	printf '%s\n' "$entry" ./src/utils/image-resize-worker.ts
	[ -f "$agent/src/extensions/codemode/worker.ts" ] && printf '%s\n' ./src/extensions/codemode/worker.ts
	return 0
}
